version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      target: development
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5433/tippmix
      - JWT_SECRET=dev-jwt-secret-key
      - FRONTEND_URL=http://localhost:3000
      - PORT=3001
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tippmix
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
