-- init.sql: Létrehoz külön sémákat a szolgáltatásoknak egyetlen adatbázison belül

\c tippster;

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS user;
CREATE SCHEMA IF NOT EXISTS post;
CREATE SCHEMA IF NOT EXISTS tipp;
CREATE SCHEMA IF NOT EXISTS chat;
CREATE SCHEMA IF NOT EXISTS notifications;
CREATE SCHEMA IF NOT EXISTS data;
CREATE SCHEMA IF NOT EXISTS image;
CREATE SCHEMA IF NOT EXISTS live;
CREATE SCHEMA IF NOT EXISTS log;
CREATE SCHEMA IF NOT EXISTS admin;
CREATE SCHEMA IF NOT EXISTS stats;
